// src/assets/fonts/fontawesome.tsx
import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faMoon, 
  faSun, 
  faBars, 
  faCheck, 
  faTimes, 
  faEnvelope, 
  faPhoneAlt, 
  faMapMarkerAlt, 
  faClock, 
  faCheckCircle, 
  faCloudUploadAlt,
  faFileAlt,
  faSpinner,
  faShoppingCart,
  faTasks,
  faMobileAlt,
  faCode,
  faCalculator,
  faChartLine,
  faArrowRight,
  faUser,
  faUserTie,
  faCopy,
} from '@fortawesome/free-solid-svg-icons';
import { 
  faLinkedinIn, 
  faGithub, 
  faFonticonsFi,
  faBehance,
  faTwitter, // Ensure you have this icon imported
} from '@fortawesome/free-brands-svg-icons';

library.add(
  faMoon, 
  faSun, 
  faBars, 
  faCheck, 
  faTimes, 
  faEnvelope, 
  faPhoneAlt, 
  faMapMarkerAlt, 
  faClock, 
  faCheckCircle, 
  faCloudUploadAlt,
  faFileAlt,
  faSpinner,
  faLinkedinIn, 
  faGithub, 
  faFonticonsFi,
  faShoppingCart,
  faTasks,
  faMobileAlt,
  faCode,
  faCalculator,
  faChartLine,
  faArrowRight,
  faBehance,
  faUser,
  faUserTie,
  faCopy,
  faTwitter
);